# Generated by Django 5.1.5 on 2025-01-26 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_detail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_detail_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
